### ISSUE TITLE
trainingの際validation関連の値が表示されない

### ISSUE THREAD

**Issue by dlpMSR** [dlpMSR/AISeminar#2]
モデルをtrainingする際，エポック毎にlossやaccuracyの値が表示されますが
validation/main/loss
validation/main/accuracy
の値が表示されません．こいつはテストデータで検証してるんでしょうか．不透明です．

なんとかしてください

**Comment by forno** [comment]
（しら）ないです

でもmnistのときもcifar10のときも表示されていないよね．
どちらかというとプログラムミスなのでは．という感じ

________________________________
差出人: Zechs Merquise <notifications@github.com>
送信日r: Tuesday, August 7, 2018 12:48:18 PM
宛先: dlpMSR/AISeminar
CC: Subscribed
件名: [dlpMSR/AISeminar] trainingのHvalidationvBのが表示されない (#2)


モデルをtrainingするH，エポック挨lossやaccuracyのが表示されますが
validation/main/loss
validation/main/accuracy
のが表示されません．こいつはテストデ`タで试^してるんでしょうか．不透明です．

なんとかしてください

―

**Comment by dlpMSR** [comment]
trainer.extend でいろいろオプションを付ける所弄ったら直った

**Comment by dlpMSR** [comment]
trainer.extend でいろいろオプションを付ける所弄ったら直った
