### ISSUE TITLE
精度上がらない問題

### ISSUE THREAD

**Issue by forno** [dlpMSR/AISeminar#3]
噂によるとDropoutよりは，BatchNormalizationの方が性能がよくなりがちらしい．

VGGちゃんは死ぬほど重たいのでご遠慮したい．
フィルタ枚数をちょっと減らした子を採用するか，重すぎVGG with BatchNormailzationを試すかのどちらかだと思う．

**Comment by dlpMSR** [comment]
ははあ。ぼく14日まで大学行けないし学外から大学のマシン触れないので、出来たらモデルのコード書いてトレーニングの実験しといてくれませんか。

**Comment by forno** [comment]
わしも同じ気持ち

**Comment by dlpMSR** [comment]
VGGで5種の料理の分類で6割程度だったし、料理って不定型なとこあるからあんまり(cifar10のような)高い精度は期待出来ないだろうね

**Comment by forno** [comment]
cifar10の画像も結構不定なとこあるけどなぁ・・・．
automobileとかもはや範囲広すぎだろワロス的なとこもある．

もうちょっと入力画像を小さくした方がうまくいくかもしれない．
入力の次元を落とすだけでも割と変わるかも．

**Comment by dlpMSR** [comment]
cifar10はhorseなら馬の部分だけがトリミングされた画像だけどこの前使った料理の画像集(food-101)はインスタに上がってる昼飯の写真みたいなものの集まりだから画像を小さくすると写ってる料理はゴミみたいに小さくなってしまう

**Comment by forno** [comment]
まあそれは一理ある．

**Comment by forno** [comment]
つまりあれだな．　　6割で満足しとこう．
とりあえず最後にNormalizationはためしとこう．

ぐらいでいいのではないだろうか．
そこそこいろいろやった感あるし

**Comment by dlpMSR** [comment]
結局精度出にくいのはそこが原因だろうな〜…としたらリサイズを224x224にしようが128x128にしようがそこまで大差ないのでは.
あとは長谷川に作って貰うhotdog/othersのデータセットで訓練してどれくらいいけるか.hotdog/sushiでVGGだと7-8割だった気がする

**Comment by dlpMSR** [comment]
発表につかうやつはゆうにゃんオリジナルのmodelにしようと思うのでいい感じの奴を作ってmodels に加えといてください．あとどのくらいの精度が期待できるものか書いといて

**Comment by forno** [comment]
そういえば閉じ忘れ．
